config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resource :basket

  resources :orders
  resources :events do
    member do
      get :delete
      delete :delete, action: :destroy
    end
  end
  resources :fulfilments, only: :create
  resources :line_items
  resources :products do
    member { get :delete }
  end
  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :suppliers, except: :show do
    member { get :delete }
  end

  root :to => 'pages#home'

  get '/outlets',  :to => 'pages#outlets'
  get '/contact',  :to => 'pages#contact'
  get '/shop', :to => 'pages#products'
  get '/signin',   :to => 'sessions#new'
  get '/signout',  :to => 'sessions#destroy'
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :order, optional: true
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)

    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end

    current_item
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  skip_before_action :authenticate

  def show
    @basket = BasketDecorator.new(FindBasket.call(id: session["basket_id"]))
  end

  def destroy
    @basket = current_basket
    @basket.destroy
    session[:basket_id] = nil
    redirect_to basket_url, notice: t("baskets.destroy.notice")
  end
end

app/views/baskets/_basket.html.erb
<div class="basket">
  <table class="table table-striped">
    <% @basket.line_items.each do |item| %>
      <tr>
        <td class="quantity"><%= button_to(
          "-",
          line_item_path(
            item,
            params: { line_item: { quantity: item.quantity - 1 } }
          ),
          class: "btn btn-mini",
          method: :patch
        ) %></td>

        <td class="quantity"><%= item.quantity %> &times;</td>

        <td class="quantity"><%= button_to(
          "+",
          line_item_path(
            item,
            params: { line_item: { quantity: item.quantity + 1 } }
          ),
          class: "btn btn-mini",
          method: :patch
        ) %></td>

        <td class="description"><%= link_to(item.product.title, product_path(item.product)) %></td>

        <td class="item-price"><%= humanize_price(item.total_price) %></td>

        <td class="destroy"><%= link_to(
          t('.destroy'),
          line_item_path(item),
          method: :delete,
          class: 'btn btn-mini btn-danger'
        ) %></td>
      </tr>
    <% end %>

    <tr class="total-line">
      <td class="total-cell" colspan="4">Total</td>

      <td class="total-cell"><%= humanize_price(@basket.total_price) %></td>

      <td></td>
    </tr>
  </table>

  <div class="form-actions">
    <%= button_to(t('.checkout'), new_order_path, class: 'btn', method: :get) %>

    <%= button_to(
      t('.empty_basket'),
      @basket,
      class: 'btn',
      method: :delete,
      data: { confirm: t('.confirm') }
    ) %>
  </div>
</div>

app/views/baskets/_empty_basket.html.erb
<div class="empty">
  <%= t(".empty") %>
</div>

app/views/baskets/show.html.erb
<%= render("layouts/header") %>

<h2><%= t('.heading') %></h2>

<%= render @basket %>

<%= render("layouts/footer") %>