config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resource :basket

  resources :orders
  resources :events do
    member do
      get :delete
      delete :delete, action: :destroy
    end
  end
  resources :fulfilments, only: :create
  resources :line_items
  resources :products do
    member { get :delete }
  end
  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :suppliers, except: :show do
    member { get :delete }
  end

  root :to => 'pages#home'

  get '/outlets',  :to => 'pages#outlets'
  get '/contact',  :to => 'pages#contact'
  get '/shop', :to => 'pages#products'
  get '/signin',   :to => 'sessions#new'
  get '/signout',  :to => 'sessions#destroy'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-block alert-error">
    <h4 class="alert-heading">
      <%= pluralize(object.errors.count, 'error') %> prohibited this from being
      saved:
    </h4>

    <ul>
      <%= render(
        partial: '/shared/full_message',
        collection: object.errors.full_messages
      ) %>
    </ul>
  </div>
<% end %>

app/views/shared/_full_message.html.erb
<li><%= full_message %></li>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <%= link_to("Radfords", root_path, class: "brand") %>

    <ul class="nav">
      <li><%= link_to("Events", events_path, class: nav_class("events")) %></li>

      <li><%= link_to(
        t('.orders'),
        orders_path,
        class: nav_class('orders')
      ) %></li>

      <li><%= link_to("Products", products_path, class: nav_class("products")) %></li>
    </ul>

    <div class="btn-group pull-right">
      <%= link_to("Sign Out", signout_path, class: "btn btn-primary btn-small") %>
    </div>
  </div>
</div>

app/views/shared/_product_button.html.erb
<div class="add-to-basket">
  <%= button_to("#{humanize_price product.price} - #{t('.add_to_basket')}", line_items_path(product_id: product)) %>
</div>