config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resource :basket

  resources :orders
  resources :events do
    member do
      get :delete
      delete :delete, action: :destroy
    end
  end
  resources :fulfilments, only: :create
  resources :line_items
  resources :products do
    member { get :delete }
  end
  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :suppliers, except: :show do
    member { get :delete }
  end

  root :to => 'pages#home'

  get '/outlets',  :to => 'pages#outlets'
  get '/contact',  :to => 'pages#contact'
  get '/shop', :to => 'pages#products'
  get '/signin',   :to => 'sessions#new'
  get '/signout',  :to => 'sessions#destroy'
end

app/views/pages/_product_button.html.erb
<div>
  <%= button_to("#{humanize_price product.price} - #{t('.add_to_basket')}", line_items_path(product_id: product)) %>
</div>

app/views/pages/_product_thumbnails.html.erb
<li class="product-thumbnail">
  <div>
    <h3><%= link_to(product.title, product_path(product)) %></h3>
  </div>

  <%= link_to(image_tag(product.photo.url(:thumbnail)), product_path(product)) %>

  <%= product_button(product) %>
</li>

app/views/pages/contact.html.erb
<%= render("layouts/header") %>

<div class="section">
  <div class="article denise">
    <%= image_tag('contact.jpg', alt: 'Denise') %>
  </div>

  <div class="article social last">
    <ul>
      <li class="email">Email
      <%= mail_to('radfords@hotmail.co.uk', 'Denise') %></li>

      <li class="facebook">
        Like our
        <a href="http://www.facebook.com/pages/Radfords-of-Somerford/170415869654554?ref=ts&amp;v=wall">Facebook</a>
        page
      </li>

      <li class="twitter">
        Follow us on <a href="http://twitter.com/r_of_somerford">Twitter</a> for
        news of upcoming events and new products.
      </li>
    </ul>
  </div>
</div>

<%= render("layouts/footer") %>

app/views/pages/home.html.erb
<%= content_for(:nav_class, "hero-nav") %>

<%= render("layouts/header") %>

<section class="home-section">
  <article class="home-blurb">
    <h2>The Company</h2>

    <p>Radfords of Somerford produces homemade foods. We do not
    use any artificial colours, preservatives, or additives, which enables our
    customers to experience the true taste of our products.</p>

    <h2>The Name</h2>

    <p>Radford is a family name which has passed on recipes
    through the generations.</p>
  </article>
</section>

<%= render "layouts/footer" %>

app/views/pages/outlets.html.erb
<%= render("layouts/header") %>

<div class="section">
  <div class="article">
    <h2>
      Farmers' Markets
    </h2>

    <p>
      We regularly attend local famers' markets / food events.
    </p>

    <ul>
      <li>
        Treacle market, Macclesfield
      </li>

      <li>
        Barclays Bank Farmers' Market (staff only), Knutsford
      </li>

      <li>
        Congleton Food Fair
      </li>
    </ul>

    <p>
      Please see the <a href="/">events/news section</a> for the latest
      information on upcoming events or follow us on
      <a href="http://twitter.com/r_of_somerford">Twitter</a> or
      <a href="http://www.facebook.com/pages/Radfords-of-Somerford/170415869654554?ref=ts&amp;v=wall">Facebook</a>.
    </p>
  </div>

  <div class="article last">
    <h2>
      Buy Direct
    </h2>

    <p>You are welcome to order products directly from us.  Please
    <%= link_to("contact us", contact_path) %> for further details.</p>
  </div>
</div>

<div class="section suppliers">
  <h2>Delicatessens / Farm Shops</h2>

  <% if @suppliers.any? %>
    <ul>
      <% @suppliers.each_with_index do |supplier, index| %><li <%= 'class=last' if ( index + 1 ) % 3 == 0 %>>
        <h3><%= supplier.name %></h3>

        <% if signed_in? %>
          <div class="actions">
            <ul>
              <li><%= link_to(
                'Edit',
                edit_supplier_path(supplier),
                class: 'btn'
              ) %></li>

              <li><%= button_to(
                'Delete',
                supplier,
                method: :delete,
                class: 'btn btn-danger'
              ) %></li>
            </ul>
          </div>
        <% end %>

        <p>
          <a href="http://maps.google.com/?q=<%= supplier.latitude %>+<%= supplier.longitude %>"><img src="//maps.google.com/maps/api/staticmap?size=290x286&amp;maptype=roadmap&amp;sensor=false&amp;center=<%= supplier.latitude %>%2C<%= supplier.longitude %>&amp;zoom=12&amp;style=feature%3Aall%7Celement%3Aall%7Csaturation%3A-100&amp;markers=color%3A0xe87eff%7C<%= supplier.latitude %>%2C<%= supplier.longitude %>" /></a>
        </p>

        <p>
          <%= raw(supplier.address.gsub("\n", '<br />')) %>
        </p>

        <% if supplier.website %>
          <p><%= link_to(supplier.website, supplier.website) %></p>
        <% end %>

        <p class="telephone">
          <%= supplier.telephone_number %>
        </p>
      </li><% end %>
    </ul>
  <% else %>
    <div class="contact-us">
      <p>We haven't got anyone supplying our products yet.</p>

      <p><a href="mailto:radfords@hotmail.co.uk">Contact us</a> about
      stocking some or all of our products.</p>
    </div>
  <% end %>

  <% if signed_in? %>
    <%= link_to 'New', new_supplier_path, class: 'btn btn-primary' %>
  <% end %>
</div>

<%= render("layouts/footer") %>

app/views/pages/products.html.erb
<%= render("layouts/header") %>

<section>
  <h1><%= t('.title') %></h1>

  <hr />

  <ul class="product-thumbnails">
    <%= render(
      partial: "product_thumbnails",
      collection: @products,
      as: :product
    ) %>
</ul>
</section>

<%= render("layouts/footer") %>