config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resource :basket

  resources :orders
  resources :events do
    member do
      get :delete
      delete :delete, action: :destroy
    end
  end
  resources :fulfilments, only: :create
  resources :line_items
  resources :products do
    member { get :delete }
  end
  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :suppliers, except: :show do
    member { get :delete }
  end

  root :to => 'pages#home'

  get '/outlets',  :to => 'pages#outlets'
  get '/contact',  :to => 'pages#contact'
  get '/shop', :to => 'pages#products'
  get '/signin',   :to => 'sessions#new'
  get '/signout',  :to => 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer role="contentinfo">
  <div class="footer-logo">
    <%= image_tag("footer_logo.svg", alt: t(".logo")) %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header role="banner">
  <%= link_to(root_path) do %>
    <%= image_tag("logo.svg", alt: t(".logo")) %>
  <% end %>

  <%= content_tag(:nav, class: [content_for(:nav_class)], role: :navigation) do %>
    <ul>
      <li class="nav-item"><%= link_to(t(".shop"), shop_path) %></li>

      <li class="nav-item"><%= link_to(t(".outlets"), outlets_path) %></li>

      <li class="nav-item"><%= link_to(t(".contact_us"), contact_path) %></li>

      <li class="nav-item"><%= link_to(
        t(".basket", item_count: @basket.item_count),
        basket_path,
      ) %></li>
    </ul>
  <% end %>
</header>

app/views/layouts/_sign_in_link.html.erb
<li><%= link_to("Sign in", signin_path) %></li>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag(
  "//fonts.googleapis.com/css?family=Open+Sans:700",
  "application"
) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body class="<%= body_class %>">
  <div class="container">
    <%= navbar %>
    <%= render "layouts/header" %>
    <div class="main">
      <%= render "flashes" -%>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </div>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>